### ISSUE TITLE
read_csv support escape_backslash

### ISSUE THREAD

**Issue by luckyrandom** [hadley/readr#127]
Although not hard to figure out that it can be down by `read_delim` with `delim = ","`, It seems more user friendly if `read_csv` support `escape_backslash`.

If it's not supported, it's helpful to document that read_csv doesn't support `escape_backslash` and redirect users to `read_delim`.

**Comment by hadley** [comment]
I'd rather leave that in `read_delim` because it's very rarely used in csv files, rarely enough that I'd claim it's not really a csv file.

The documentation seems reasonably clear to me currently - "read_csv and read_tsv are special cases of the general read_delim". And they're all documented in the same place so you can see which arguments they take.
