### ISSUE TITLE
Implement write_tsv

### ISSUE THREAD

**Issue by hadley** [hadley/readr#135]
Should be simple generalisation of `write_csv`. Use same strategy to only quote when needed.

**Comment by nicolasCoutin** [comment]
@hadley I've been reading through your [r-pkgs book](http://r-pkgs.had.co.nz/) book and I'm learning me how to package. It's very helpful! Anyway since I wanted to walkthrough the process with a simple use case:  

 i decided to make [`writer`](https://github.com/nicolasCoutin/writer) where I (stole! and) generalised `readr:::stream_csv()` to `stream_delim()` and used it to implement:   

-  `write_csv()` 
- `write_tsv()`  
- `write_delim()`  

 I also threw in naive wrappers around `base::saveRDS` to make:
- `write_rds()` 
- `write_compressed_rds()`  

Now although this was purely an exercise to get learning.. it got me wondering: If `readr` is about reading then should you have a `writer` (or maybe `saver` since it has 5 letters) package? And if `readr` is really about stable/streaming data input and output should it then be renamed to reflect this? I guess I'm really asking about the phylosophy of how package-happy one should be when developing thingamabobs.

I hope it's helpful with this issue!
If you have any thoughts `rep(c('thanks', '!'),1E6`)

**Comment by hadley** [comment]
I'd rather just keep all the functionality in readr - I don't think it's too awful to keep the name as readr, since that is the primary purpose. Do you want to do a pull request?

**Comment by nicolasCoutin** [comment]
@hadley okee: see #157
