### ISSUE TITLE
Matching the extra columns specified in col_types

### ISSUE THREAD

**Issue by byzheng** [hadley/readr#145]
I would like to specify the column types using arguments `col_types` when I read the csv files. However, the column number could be different in my multiple csv files (Some files include extra column). 

When I specify extra column types and get an error messages:

    Error: The following named parsers don't match the column names: sow_date1

It will be better to let us to specify extra columns for flexibility (or give a warning message).

**Comment by alyst** [comment]
+1. `read_xxx()` should not stop if there are no problems with the table format or type specification for existing columns. With the current behaviour it's hard to read the files with the variable sets of columns, because one doesn't know in advance what columns would be available.
If there's a typo in `col_types` specification, just a warning should be enough. If the user wants to enforce the existence of the columns, it's also easy to do from the user code.
