### ISSUE TITLE
col_factor() requires a known set of factors

### ISSUE THREAD

**Issue by MySchizoBuddy** [hadley/readr#161]
col_factor() requires a known set of factors. It should have a default option of reading the column as a factor without having to know in advance which factors are used in the file.

**Comment by hadley** [comment]
If you don't know in advance what the possible set of values are, it's not a factor.

**Comment by joehl** [comment]
Hi Hadley,
there are a couple of reasons to desire that one can read a colun with unknown levels as a factor. It's also desirable that one can read a column with known levels and still collect new unknown strings as factor levels rather than coding them NA. One reason that come up to my mind are 1) human errors, say someone tells you the colum has values in a certain spelling, but actually the spelling is different. Reeason 2) is that one would wish using readr as a faster replacement for read.csv when reading data with read.csv.ffdf and ffdf does - for good reasons - not support stringbut only factors. The incremental chunk reading in ffdf requires that each chunk may add new levels while keeping the codes of the previous levels invariant. The worst thing that can happen is that we end up with unwanted levels: with a factor these are easily tabulated and replaced by NA, e.g. with a convenience function. If there are very many rows with unknown levels, your error logging can impact performance. Why not just log the occurence of unknown levels once together with the set of expected levels and return the hcolumn with all levels encountered?
Cheers
Jens Oehlschlägel

**Comment by jennybc** [comment]
I can't believe I'm advocating for factors upon import 😱. But I am.

Sometimes you just want a factor and you're OK with the levels being all unique values, in alphabetical order.

Current example: Gapminder data. I want `country` as a factor and there are hundreds of levels. There's no way I'm specifying those in `col_factor()`. Even when I take charge of these levels, it's via `reorder()`, I never handle them directly.

Would you consider having the `levels` argument of `parse_factor()` behave like that of `factor()` by default?

**Comment by hadley** [comment]
@jennybc I still think you should do this after the fact with `factor()`. But I'd review PR that added an option to do this (defaulting to FALSE)
