### ISSUE TITLE
Is it possible to give read_table() the option to expand tabs?

### ISSUE THREAD

**Issue by rpruim** [hadley/readr#168]
I realize that one could use `read_tsv()` when one has a genuine tsv file, but it appears to me that `read_table()` doesn't handle tsv files well.  It would be nice to be able to read columnar data that uses a mix of spaces and tabs to align the columns.  This might require providing an integer to specify how many spaces apart the "tab stops" are, but perhaps this can be sniffed from the first 100 lines if no value is provided.

**Comment by hadley** [comment]
Are there really files that do this??

**Comment by robertzk** [comment]
If the number of spaces per tab is fixed, why not run the file through a [`sed`](http://www.brunolinux.com/02-The_Terminal/Find_and%20Replace_with_Sed.html) first?

**Comment by hadley** [comment]
I'd be willing to accept a PR that implemented this, but it's unlikely I'll do it myself. It shouldn't be too hard - there's a little bit of C++ code involved as you'll need to think how to rewrite this for loop:

```cpp
  // Find the end of the field, stopping for newlines
  for(int i = 0; i < width; ++i) {
    if (fieldEnd == end_ || *fieldEnd == '\n' || *fieldEnd == '\r') {
      warn(row_, col_, tfm::format("%i chars", width), tfm::format("%i", i));

      tooShort = true;
      break;
    }

    fieldEnd++;
  }
```

Although it might be more complicated than that because you'll need to rethink the beginning and end offsets for each field.
