### ISSUE TITLE
Expand to parallel chunk reading

### ISSUE THREAD

**Issue by joehl** [hadley/readr#207]
In #206 I have suggested to allow a aprox chunk size parameter read_approx_bytes=.
An extension of this logic even allows *parallel* reading from a csv-file
(Some people have fast SANs that support parallel read-processes, even consumer PCIe SSDs are there now, e.g. Intel SSD 750)

process 1
read_csv(con, skip_approx_bytes=0, read_approx_bytes=5000)
process 2
read_csv(con, skip_approx_bytes=5000, read_approx_bytes=5000)

Here an additional challenge is that process 2 can't wait until process 1 figured out the exact position of the next row-break
however, if we read an csv format that disallows line-breaks in strings we can simply move from the specified skip_approx_bytes position until we find the next line-break, there the process starts reading read_approx_bytes, and then continues reading until the row is exhausted
A separate function which does just the position finding is useful

approx_csv(file, approx_bytebreaks) -> returns exact_bytebreaks
for example
approx_csv(file, c(0, 5000)) -> returns e.g. c(0, 5003)

this allows for example preparing an ffdf file of appropriate size
and all parallel processes can independently write their read data.frame into their section of the ffdf
this gives completely lock-free parallelism.
Note that sizing an ffdf only works because ffdf has constant record-size, i.e. factors instead of character (see #161)

**Comment by hadley** [comment]
I think the key challenge of parallel reads is that R's C API is not thread safe, so we'd have to do everything in C++. That means either creating another complete copy of the data in memory (bad) or rewriting a lot of C API ourselves. I don't think that's too bad for simple types (since e.g. integers are just an array under the hood), but it makes resizing hard, and I have no idea how to deal with strings.
