### ISSUE TITLE
read_tsv results no "true" data.frame

### ISSUE THREAD

**Issue by holtgrewe** [hadley/readr#362]
I have a problem using the result of `read_csv` as a `data.frame` type Slot in an R4 class. The following piece of code

```
require(readr);

MyClass = setClass("MyClass",
                   representation = representation(the_data = "data.frame"));

read_from_csv = function(path, splitters) {
    data = read_csv("foo,bar\nbaz,rex\n", col_types="cc", col_names=c("one", "two"));

    result = new("MyClass", the_data = data);
    return (result);
}

read_from_csv();
```

gives the following error message.

```
Error in validObject(.Object) : 
  invalid class “MyClass” object: 1: invalid object for slot "the_data" in class "MyClass": got class "tbl_df", should be or extend class "data.frame"
invalid class “MyClass” object: 2: invalid object for slot "the_data" in class "MyClass": got class "tbl", should be or extend class "data.frame"
invalid class “MyClass” object: 3: invalid object for slot "the_data" in class "MyClass": got class "data.frame", should be or extend class "data.frame"
```

The following works fine.

```
MyOtherClass = setClass("MyOtherClass",
                   representation = representation(the_data = "data.frame"));

read_from_csv = function(path, splitters) {
    data = read.csv(header = FALSE, col.names = c("one", "two"), text = "foo,bar\nbaz,rex\n");
    
    result = new("MyOtherClass", the_data = data);
    return (result);
}

read_from_csv();
```

**Comment by joranE** [comment]
This is probably because the readr functions actually return objects with a class attribute of `tbl_df`, `tbl`, `data.frame`. I suspect that explicitly coercing the result of `read_csv` via `as.data.frame` will solve the problem.

I think that it would perhaps be clearer if the documentation for these functions actually specified this. Rather than simply saying "A data frame" in the Value section of the documentation, they might specify that it returns a `tbl_df` and made some indication that some differences in behavior should be expected.

**Comment by hadley** [comment]
If you load tibble this problem will go away.
