### ISSUE TITLE
Also include easy way to get into sqlite?

### ISSUE THREAD

**Issue by hadley** [hadley/readr#48]
Should be able to generate good sql after reading first few columns.

**Comment by hadley** [comment]
Tabling for now

**Comment by saurfang** [comment]
Ah I really wanted to see this feature. Any chance you can describe what you have in mind on a high level? I'm happy to give it an attempt if you think this isn't terribly difficult. My concern is really that if someone want to load this to sqlite it is because the data is too big to fit in the memory, such that the process needs to be streaming rather than shoveling it altogether from R.
