### ISSUE TITLE
Parsing 

### ISSUE THREAD

**Issue by sjspielman** [hadley/readr#482]
The function read_csv() returns "Warning: <x> parsing failures" for certain .csv files which were created with write_csv(). The issue seems to occur only for *large*, i.e. >=60 MB, files (unfortunately, github won't let me upload a file > 10MB so I can't share an example case here). A visual examination of csv files written w/ write_csv() look fine, so the issue appears to be with read_csv()'s parsing, not write_csv()'s writing.

**Comment by hadley** [comment]
Can you please create a minimal example (maybe just writing some of the lines). Otherwise it's hard for us to narrow down the problem.

**Comment by sjspielman** [comment]
I was able to get it down to a manageable github-friendly size - a compressed csv file that gives these warnings is attached. Let me know if this works!
[testcase.csv.zip](https://github.com/hadley/readr/files/368153/testcase.csv.zip)

**Comment by hadley** [comment]
From a quick look, I'd say it's because the first 12500 values of `ds` are all integers, so readr guesses the wrong type (and the plot `plot(x$ds - round(x$ds))` shows quite an interesting pattern). In general you shouldn't expect perfect symmetry between `read_csv()` and `write_csv()` because csv loses information about the types.

In this case however, `write_csv()` could add a trailing `.0` to integer doubles to make sure they are correctly imputed on read. @jimhester, what do you think?

**Comment by jimhester** [comment]
We could do this, but it would require modifying the grisu3 output code (which I would prefer avoiding). It would also increase file sizes for the csv's, although I don't think that is a major concern.

**Comment by jimhester** [comment]
#483 Has the implementation for this, it turned out to not be too tricky. Up to you if we want to go this route or not.
