### ISSUE TITLE
Need some way to specify that you only want certain columns

### ISSUE THREAD

**Issue by hadley** [hadley/readr#72]
```R
col_types = only("a", "k", "z")

col_types = only("a", "k", z = col_factor(c("a","b")))
```

??

**Comment by HenrikBengtsson** [comment]
Since I'm just starting to look into readr, it might be that I'm unaware of some existing features of the package, so please forgive me if that's the case.  If not, have a look at how I do it in `R.filesets::readDataFrame()`.  Maybe you can enhance `col_types` to support named character vectors as well.  Example:
```r
readDataFrame(pathname, colClasses=c("*"="NULL", "(x|y)"="integer", "char"="character"))
```
Here `names(colClasses)` specified regular expression matching column names.  The `"*"=NULL` specifies that the default column class should be NULL, i.e. to drop/skip all columns by default, except those specified.

In your case I can imagine something like:
```r
read_tsv(pathname, col_types=list("*"=col_skip(), x=col_integer(), y=col_integer(), char=col_character()))
```
An alternative is to let an empty name represent the default behavior.

You could also extend `col_types` to also support:
```r
read_tsv(pathname, col_types=c("*"="_", x="i", y="i", char="c"))
```
such that it expands to the above list.  With empty name for default, you'd have:
```r
read_tsv(pathname, col_types=c("_", x="i", y="i", char="c"))
```

**Comment by hadley** [comment]
I'm not a big fan of overloading column names with additional structure. What happens if there is a column called `*`?

**Comment by HenrikBengtsson** [comment]
That's why I proposed the empty-name alternative.  Of course, then there could be empty column names as well.  Using regular expressions handles it all, but you'd need to escape.
